---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sql-volume-claim
  labels:
    type: sql_pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector: 
    matchLabels:
      type: sql_pv