---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume-claim
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
 